spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_study?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    data-username: root
    data-password: root
  jpa:
    hibernate:
      ddl-auto: update  # 第一次创建表create  后面用update
      show-sql: true

